#!/usr/bin/env python3
"""maketables.py — generate ROM data tables for sndj.

Emits into the build directory:
  schemes.bin  — 8 palette schemes x 16 bytes (marker-wrapped SNPAL0 in ROM;
                 the engine builds CGRAM + the HDMA gradient from these at
                 apply time). Per scheme, little-endian 15-bit BGR words:
                 bg, text, dim, accent, hilite, then padding (solid
                 backdrop — no gradient).

Scheme 0 is the sndj house style; 1-7 follow genmddj's palette set
(BLK / WHT / KIDD / AMBR / CYAN / PINK / MINT) so the family reads the
same across consoles. PALETTE.md documents them.
"""
import sys


def bgr15(r, g, b):
    """r,g,b 0-255 -> SNES 15-bit BGR."""
    return ((b >> 3) << 10) | ((g >> 3) << 5) | (r >> 3)


# --- palette schemes ---------------------------------------------------------
# Slots per scheme: bg, text, dim, accent, hilite, gradient top, gradient
# bottom. Scheme 0 is the house style; 1-7 mirror genmddj (its MD nibble
# levels mapped through the MD DAC ramp to 8-bit).

SCHEMES = [
    # genmddj's 8 schemes: two colours each (bg, text). The cursor and
    # playheads render as palette negatives; dim derives from the pair.
    ('BLK ', (0, 0, 0),       (255, 255, 255)),
    ('WHT ', (255, 255, 255), (0, 0, 0)),
    ('KIDD', (0, 87, 206),    (255, 255, 0)),
    ('AMBR', (52, 0, 0),      (255, 172, 0)),
    ('CYAN', (0, 0, 87),      (0, 255, 255)),
    ('PINK', (87, 0, 87),     (255, 0, 255)),
    ('NEON', (87, 172, 255),  (255, 0, 172)),
    ('MINT', (0, 87, 87),     (87, 255, 172)),
]


def schemes_bin():
    out = bytearray()
    for name, bg, text in SCHEMES:
        for c in (bg, text):
            w = bgr15(*c)
            out += bytes((w & 0xFF, w >> 8))
        out += bytes(12)  # pad to 16
    return bytes(out)


def scheme_names_inc():
    return ("pal_names:\n" +
            "".join(f'    .DB "{n}"\n' for n, *_ in SCHEMES))


# --- pitch table -------------------------------------------------------------
# DSP pitch is 14-bit; $1000 plays a sample at its native rate. The table
# holds the TOP octave (octave 7: C-7=$4000) as 16-bit values; the engine
# right-shifts by (7 - octave). This is the single tuning source — the same
# numbers are exported to sndj.js (M11+) so browser previews match hardware.

def pitch_octave7():
    return [round(0x4000 * 2 ** (s / 12)) for s in range(12)]


def default_waves():
    import math as m
    waves = []
    waves.append([round(7.5 + 7.4 * m.sin(2 * m.pi * i / 32)) for i in range(32)])   # sine
    waves.append([round(abs((i / 16) % 2 - 1) * 15) for i in range(32)])             # tri
    waves.append([round(i * 15 / 31) for i in range(32)])                            # saw
    waves.append([15 if i < 16 else 0 for i in range(32)])                           # square
    waves.append([15 if i < 8 else 0 for i in range(32)])                            # pulse 25
    waves.append([15 if i < 4 else 0 for i in range(32)])                            # pulse 12
    waves.append([round(7.5 + 3.7 * m.sin(2 * m.pi * i / 32)
                        + 3.7 * m.sin(6 * m.pi * i / 32)) for i in range(32)])       # organ
    rnd = [11, 3, 14, 6, 9, 1, 12, 15, 4, 8, 0, 13, 5, 10, 2, 7,
           14, 5, 1, 12, 8, 15, 3, 9, 6, 0, 11, 4, 13, 2, 10, 7]                    # gritty
    waves.append(rnd)
    return [[max(0, min(15, v)) for v in w] for w in waves]


def tables_inc():
    lines = ["; generated by tools/maketables.py — do not edit", ""]
    vals = pitch_octave7()
    lines.append("pitch_octave7:  ; C-7..B-7 base pitches, >> (7-octave)")
    lines.append("    .DW " + ", ".join(f"${v:04X}" for v in vals))
    lines.append("")
    # note (0..95, C-0..B-7) -> semitone*2 (word index) and shift (7-oct)
    lines.append("note_semi2:  ; note -> semitone*2 (pitch_octave7 word offset)")
    for o in range(8):
        lines.append("    .DB " + ", ".join(str((n % 12) * 2) for n in range(o * 12, o * 12 + 12)))
    lines.append("note_shift:  ; note -> right-shift count (7-octave)")
    for o in range(8):
        lines.append("    .DB " + ", ".join(str(7 - o) for _ in range(12)))
    lines.append("")
    lines.append("default_waves:  ; 8 banks x 32 samples, 4-bit (seeded by NEW)")
    for w in default_waves():
        lines.append("    .DB " + ", ".join(f"${v:X}" for v in w))
    lines.append("")
    return "\n".join(lines) + "\n"


# --- factory kits ------------------------------------------------------------
# 16 kits x 16 slots x 4 bytes (pool sample, tune, vol, flags); vol 0 =
# empty slot. Marker-wrapped SNKIT0 in ROM; song NEW copies the block
# verbatim into the song's kit section, and patcher.html edits it.
# Only kit 0 (SMW percussion) ships filled — the factory boot set stays
# small so the pool loads on demand (residency follows references).
# Kits 1-15 are blank canvases for the patcher's kit builder / the
# console KIT screen. 8 kHz drums: tune -24 ($E8), vol $50.

FACTORY_KITS = [(16, 10)]  # (first pool sample, count)


def kits_bin():
    # the committed factory (.sndjfact from patcher.html) is the truth;
    # a bare kits.bin also works; else generate from the table
    import os.path
    if os.path.exists('samples/factory.sndjfact'):
        with open('samples/factory.sndjfact', 'rb') as f:
            d = f.read()
        assert d[:8] == b'SNDJFACT' and d[8] in (1, 2), 'factory.sndjfact: bad magic'
        plen = d[12] | (d[13] << 8) | (d[14] << 16)
        return d[16 + plen:16 + plen + 1024]
    if os.path.exists('samples/kits.bin'):
        with open('samples/kits.bin', 'rb') as f:
            data = f.read()
        assert len(data) == 1024, 'samples/kits.bin must be 16*16*4 bytes'
        return data
    out = bytearray(16 * 16 * 4)
    for k, (base, count) in enumerate(FACTORY_KITS):
        for s in range(count):
            off = k * 64 + s * 4
            out[off:off + 4] = bytes((base + s, 0xE8, 0x50, 0))
    return bytes(out)


def defaults_bin():
    # SNDEF2: 12 boot instruments as three rows (types, samples/kits/
    # banks, extras — record byte 7: SLICES-1 high nibble, EON bit 0).
    # Older factory files carry 8-wide rows (v1 two, v2 three): re-stride
    # and pad the new slots with SMP on sample 0.
    import os.path
    if os.path.exists('samples/factory.sndjfact'):
        with open('samples/factory.sndjfact', 'rb') as f:
            d = f.read()
        plen = d[12] | (d[13] << 8) | (d[14] << 16)
        off = 16 + plen + 1024
        if d[8] >= 3:
            return d[off:off + 36]
        rows = 3 if d[8] == 2 else 2
        out = bytearray(36)
        for r in range(rows):
            out[r * 12:r * 12 + 8] = d[off + r * 8:off + r * 8 + 8]
        return bytes(out)
    return bytes((0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
                  0, 1, 2, 3, 4, 5, 6, 0, 0, 0, 0, 0,
                  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0))


def main(build_dir):
    sch = schemes_bin()
    with open(f'{build_dir}/schemes.bin', 'wb') as f:
        f.write(sch)
    kits = kits_bin()
    with open(f'{build_dir}/kits.bin', 'wb') as f:
        f.write(kits)
    defs = defaults_bin()
    assert len(defs) == 36, 'defaults.bin must be 36 bytes'
    with open(f'{build_dir}/defaults.bin', 'wb') as f:
        f.write(defs)
    with open(f'{build_dir}/tables.inc', 'w') as f:
        f.write(tables_inc())
        f.write(scheme_names_inc())
    print(f"maketables: schemes.bin ({len(sch)}), kits.bin ({len(kits)}), "
          f"defaults.bin, tables.inc")


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else 'build')
